# Generated by Django 5.1.2 on 2024-12-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_home_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='home',
            name='history',
        ),
        migrations.RemoveField(
            model_name='home',
            name='links',
        ),
        migrations.AlterField(
            model_name='home',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='events',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='research',
            field=models.TextField(),
        ),
    ]
